type HslaColor = {
    h: number;
    s: number;
    l: number;
    a: number;
    ads?: string;
};
declare const BaseColors: readonly ["red", "redDark", "blurpleLight", "blurpleMedium", "blurple", "blurpleDark", "blurpleStrong", "offWhite", "blueLight", "blue", "blueDark", "magentaLight", "magenta", "magentaDark", "orangeLight", "orange", "orangeDark", "purple", "purpleDark", "purpleLight", "tealLight", "teal", "tealDark", "yellowLight", "yellow", "yellowDark"];
declare const GreyColors: readonly ["grey8", "grey7", "grey6", "grey5", "grey4", "grey3", "grey2", "grey1", "white"];
declare const SharedColors: readonly ["record", "recordHover", "recordActive", "backdropDark", "backdropTwilight", "highlight", "highlightHover", "highlightActive", "warning"];
declare const SemanticColors: readonly ["primary", "primaryHover", "primaryActive", "body", "bodyDimmed", "bodyInverse", "background", "backgroundHover", "backgroundActive", "backgroundNeutral", "backgroundNeutralHover", "backgroundNeutralActive", "backgroundSecondary", "backgroundSecondary2", "backgroundInverse", "focusRing", "overlay", "overlayHover", "overlayActive", "backdrop", "border", "disabledContent", "disabledBackground", "formFieldBorder", "formFieldBackground", "buttonBorder", "upgrade", "upgradeHover", "upgradeActive", "tabBackground", "discoveryBackground", "discoveryLightBackground", "discoveryTitle", "discoveryHighlight", "info", "success", "danger", "dangerHover", "dangerActive", "illustrationAccent", "illustrationOrange", "illustrationLine", "illustrationPurple", "illustrationGreen", "illustrationGray", "illustrationAccentGray", "illustrationStroke", "illustrationDrawer", "illustrationPaper", "illustrationInnerPaper", "illustrationGreenShade", "illustrationBlueDark", "illustrationFace", "illustrationRainstormGray", "illustrationCheckBlue", "illustrationGreyscaleFill", "illustrationGreyscaleAccent", "illustrationGreyscaleMid", "illustrationGreyscaleMidDark", "illustrationGreyscaleDark", "illustrationGreyscaleStroke", "illustrationBg"];
type ThemesColorVariant = Record<(typeof SharedColors)[number] | (typeof SemanticColors)[number], HslaColor>;
type ThemesColors = {
    light: ThemesColorVariant;
    dark: ThemesColorVariant;
};
export declare const darken: (color: HslaColor, percentage: number) => HslaColor;
export declare const lighten: (color: HslaColor, percentage: number) => HslaColor;
export declare const saturate: (color: HslaColor, percentage: number) => HslaColor;
export declare const alphaFunction: (color: HslaColor, alpha: number) => HslaColor;
export declare const hslaBaseColors: Record<(typeof BaseColors)[number], HslaColor>;
export declare const hslaGreys: Record<(typeof GreyColors)[number], HslaColor>;
export declare const themeColors: ThemesColors;
export declare const illustrationColors: {
    staticDarkBlue: string;
    staticRed: string;
};
export declare const hslaColors: {
    grey8: HslaColor;
    grey7: HslaColor;
    grey6: HslaColor;
    grey5: HslaColor;
    grey4: HslaColor;
    grey3: HslaColor;
    grey2: HslaColor;
    grey1: HslaColor;
    white: HslaColor;
    red: HslaColor;
    redDark: HslaColor;
    blurpleLight: HslaColor;
    blurpleMedium: HslaColor;
    blurple: HslaColor;
    blurpleDark: HslaColor;
    blurpleStrong: HslaColor;
    offWhite: HslaColor;
    blueLight: HslaColor;
    blue: HslaColor;
    blueDark: HslaColor;
    magentaLight: HslaColor;
    magenta: HslaColor;
    magentaDark: HslaColor;
    orangeLight: HslaColor;
    orange: HslaColor;
    orangeDark: HslaColor;
    purple: HslaColor;
    purpleDark: HslaColor;
    purpleLight: HslaColor;
    tealLight: HslaColor;
    teal: HslaColor;
    tealDark: HslaColor;
    yellowLight: HslaColor;
    yellow: HslaColor;
    yellowDark: HslaColor;
};
export declare const colorsNames: string[];
export {};
//# sourceMappingURL=colors.d.ts.map