type VarsObject = Record<string, string | number>;
export declare const getCssVarsFromObject: (prefix: string, varsObject: VarsObject) => VarsObject;
export declare const unitVariables: VarsObject;
export declare const fontWeightVariables: VarsObject;
export declare const fontSettingVariables: VarsObject;
export declare const textSizeVariables: VarsObject;
export declare const radiusVariables: VarsObject;
export declare const shadowVariables: VarsObject;
export declare const spaceVariables: VarsObject;
export declare const formFieldVariables: VarsObject;
export declare const gradientVariables: VarsObject;
export declare const getSizingVariablesCssVarsObject: () => VarsObject;
export declare const getVariablesCssVarsObject: () => VarsObject;
export declare const getColorsCssVarsObject: () => VarsObject;
export declare const getThemeStylesString: (customRootElement?: string) => string;
export declare const getThemeStyles: () => void;
export declare const getSizingCssVarsDeclarations: () => string;
export declare const getAllCssVarsString: (customRootElement: any) => string;
export {};
//# sourceMappingURL=index.d.ts.map